sudo: false

language: Python
python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - MAKE_MINICONDA=1 source .travis_env_setup.sh

script:
  - python -c "from btax import *" && echo B-Tax can be imported
  - coverage run -m py.test -v -m "not slow and not needs_puf" btax --pep8

